name: Docker Jekyll CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image for Jekyll
      run: docker build . --file Dockerfile --tag jekyll-site:latest

    - name: Run Jekyll to build the site
      run: docker run --rm -v $(pwd):/srv/jekyll -v $(pwd)/_site:/srv/jekyll/_site jekyll-site:latest jekyll build

    - name: Archive site content
      uses: actions/upload-artifact@v3
      with:
        name: site-content
        path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download site content
      uses: actions/download-artifact@v3
      with:
        name: site-content

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: _site
